# FROM: https://github.com/dependabot/dependabot-core/issues/1973#issuecomment-701889737
#  and: https://github.com/pascalgn/automerge-action/issues/114#issue-713414227
name: "Dependabot Automerge - Action"
on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
  pull_request_review:
    types:
      - submitted
  check_suite:
    types:
      - completed
  status: {}
jobs:
  automerge-dependabot:
    runs-on: ubuntu-latest
    steps:
      - name: automerge
        uses: "pascalgn/automerge-action@v0.12.0"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_FILTER_AUTHOR: "dependabot[bot]"
